"""posts table

Revision ID: 15646fb0449a
Revises: 6a3c27dda6c2
Create Date: 2020-05-20 17:20:53.982024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15646fb0449a'
down_revision = '6a3c27dda6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('answer', sa.VARCHAR(length=720), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
