"""posts table

Revision ID: c6e35f0eefce
Revises: c9aad1aa4605
Create Date: 2020-05-20 16:51:42.381944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e35f0eefce'
down_revision = 'c9aad1aa4605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('question', sa.String(length=720), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'question')
    # ### end Alembic commands ###
